### ISSUE TITLE
Add reminder link checking to Coast Guard

### ISSUE THREAD

**Issue by rpmjade** [rpmsoftware/coast-guard#5]
@rpmjoaquin add functionality to Coast Guard to verify the URL in the "View in" button in the reminder emails so that it would have caught #1463. This may be difficult because the links are replaced by mandrill redirections. Any ideas?

FYI @jeremyrpm

**Comment by rpmjade** [comment]
Let's do it, but this is low priority. Dedicated email account is fine, setup a gmail account if that service works and make sure to add it to the Service list in Hub

**Comment by jwindmuller** [comment]
@rpmjade @jeremyrpm This is now live and tomorrow the Coast Guard email should come with a new section for this test ("Test: Notification email")

What it does:

1. It logs in into rpm.coastguard@gmail.com
2. Finds the notification email for the new actions
3. Finds the `View in BRAND` email 
4. "Clicks" the link and checks that the final URL for that link is correct (something like this: `https://<domain_for_brand>/rpm/page/form.aspx?item=<FormID>`).
