### ISSUE TITLE
Switch email sending to SendGrid

### ISSUE THREAD

**Issue by rpmjade** [rpmsoftware/coast-guard#6]
We have moved all RPM primary email sending from Mandrill to SendGrid. We might get rid of Mandrill so make sure anything that was using Mandrill moves to SendGrid. Let me know if there are services other than Coast Guard that also need issues. There should be one services account used by all the non-rpm applications. Please create it and add to Hub Services.

**Comment by jwindmuller** [comment]
Done, tomorrow's email may look the same or just be a total failure. I will keep an eye open.

/cc @rpmjade @jeremyrpm
